### ISSUE TITLE
Dados do Boleto

### ISSUE THREAD

**Issue by Hamdan85** [mcrvaz/boleto-brasileiro-validator#1]
Ola, tudo bem?

Somente para perguntar... existe a possibilidade de extração de dados do boleto?

**Comment by mcrvaz** [comment]
Olá, @Hamdan85 , desculpe pela demora.
Atualmente não existe a possibilidade de extração dos dados do boleto, mas [aqui](https://github.com/mcrvaz/boleto-brasileiro-validator/blob/master/src/conversor.js) existe um exemplo de como realizar conversão entre tipos de boletos, e lá estão definidos os valores de cada campo, caso te ajude.

**Comment by Hamdan85** [comment]
Ola @mcrvaz ... 
ja consegui as informações. Se quiser adicionar a funcionalidade ao seu pacote, pode serguir o desenvolvido nessa gem aqui: 
https://github.com/Hamdan85/VerificadorBoletoBr
