### ISSUE TITLE
Python: portabilidade

### ISSUE THREAD

**Issue by leomaurodesenv** [mcrvaz/boleto-brasileiro-validator#21]
Olá, gostaria de desenvolver a portabilidade deste código para Python, ou se alguém já tiver feito - gostaria de contribuir com o projeto.

**Comment by mcrvaz** [comment]
Oi @leomaurodesenv, atualmente não estou mais ativamente mantendo esse projeto, porém a licença é MIT, então fique à vontade para fazer a portabilidade para Python.

**Comment by leomaurodesenv** [comment]
Certo, obrigadão!
